### ISSUE TITLE
Apparently it does not compile with sip4.19.1. It worked fine with previous sip4.18.1. (win7 32, python27) 

### ISSUE THREAD

**Issue by dfcarreiras** [esrf-bliss/Lima#47]
this is the error message:
rror when reaching the  windowsSipCompilation.py. This 
> is it:
>
> Microsoft (R) Program Maintenance Utility Version 9.00.21022.08
> Copyright (C) Microsoft Corporation.  All rights reserved.
>
>         cl -c /EHsc /DWITH_CONFIG -I"." -I"..\core" 
> -I"..\..\third-party\Process
> lib\sip" -I"C:\Python27\lib\site-packages\numpy\core\include" 
> -I"C:\Python27\inc
> lude" -I"..\..\third-party\Processlib\core\include" 
> -I"..\..\third-party\Process
> lib\tasks\include" 
> -I"..\..\third-party\Processlib\core\include\WindowSpecific"
> -I"..\..\common\include" -I"..\..\hardware\include" 
> -I"..\..\control\include" -I
> "..\..\control\software_operation\include" -nologo -Zm200 -Zc:wchar_t- 
> -O2 -MD -
> W3 -w34100 -w34189 -DNDEBUG -DUNICODE -DWIN32 -DQT_LARGEFILE_SUPPORT 
> -I. -I..\co
> re -I..\..\third-party\Processlib\sip 
> -IC:\Python27\lib\site-packages\numpy\core
> \include -IC:\Python27\include 
> -I..\..\third-party\Processlib\core\include -I..\
> ..\third-party\Processlib\tasks\include 
> -I..\..\third-party\Processlib\core\incl
> ude\WindowSpecific -I..\..\common\include -I..\..\hardware\include 
> -I..\..\contr
> ol\include -I..\..\control\software_operation\include -Fo 
> @C:\Users\WINDOW~1\App
> Data\Local\Temp\nm2FA4.tmp
> lima_init_numpy.cpp
> siplimacorecmodule.cpp
> ../../control/sip/CtConfig.sip(300) : error C2065: 
> 'sipExportedExceptions_limaco
> re' : undeclared identifier
> ../../common/sip/Exceptions.sip(41) : error C2065: 
> 'sipExportedExceptions_limaco
> re' : undeclared identifier
> ../../common/sip/Exceptions.sip(41) : error C2065: 
> 'sipExportedExceptions_limaco
> re' : undeclared identifier
>
> ...

**Comment by dfcarreiras** [comment]
Many thanks again all the team for all these efforts. David Fernández
