### ISSUE TITLE
Does not build with sip 4.19.3

### ISSUE THREAD

**Issue by birkenfeld** [esrf-bliss/Lima#58]
With sip 4.19.3, I get the following errors while building `make -C sip`:
```
g++ -c -pthread -g -DWITH_SPS_IMAGE -I"." -I"../core" -I"../../third-party/Processlib/sip" -I"/usr/local/lib/python2.7/site-packages/numpy/core/include" -I"/usr/local/include/python2.7" -I"../../third-party/Processlib/tasks/include" -I"../../third-party/Processlib/core/include" -I"../../common/include" -I"../../hardware/include" -I"../../control/include" -I"../../control/software_operation/include" -pipe -fPIC -O2 -Wall -W -DNDEBUG -I. -I../core -I../../third-party/Processlib/sip -I/usr/local/lib/python2.7/site-packages/numpy/core/include -I/usr/local/include/python2.7 -I../../third-party/Processlib/tasks/include -I../../third-party/Processlib/core/include -I../../common/include -I../../hardware/include -I../../control/include -I../../control/software_operation/include -o siplimacorestdlist0100SoftOpRoi2SpectrumRoiNameAndTask.o siplimacorestdlist0100SoftOpRoi2SpectrumRoiNameAndTask.cpp
../../control/software_operation/sip/SoftOpId.sip: In function ‘int convertTo_std_list_0100SoftOpRoi2Spectrum_RoiNameAndTask(PyObject*, void**, int*, PyObject*)’:
../../control/software_operation/sip/SoftOpId.sip:614: error: ‘sipType_Tasks_Roi2SpectrumTask’ was not declared in this scope
../../control/software_operation/sip/SoftOpId.sip:627: error: ‘sipType_Tasks_Roi2SpectrumTask’ was not declared in this scope
../../control/software_operation/sip/SoftOpId.sip: In function ‘PyObject* convertFrom_std_list_0100SoftOpRoi2Spectrum_RoiNameAndTask(void*, PyObject*)’:
../../control/software_operation/sip/SoftOpId.sip:655: error: ‘sipType_Tasks_Roi2SpectrumTask’ was not declared in this scope
make[1]: *** [siplimacorestdlist0100SoftOpRoi2SpectrumRoiNameAndTask.o] Error 1
```
I can get rid of these errors using `#include "sipAPIprocesslib.h"` in the `%TypeHeaderCode` sections of `control/software_operation/sip/SoftOpId.sip`. But then I get the following:
```
g++ -c -pthread -g -DWITH_SPS_IMAGE -I"." -I"../core" -I"../../third-party/Processlib/sip" -I"/usr/local/lib/python2.7/site-packages/numpy/core/include" -I"/usr/local/include/python2.7" -I"../../third-party/Processlib/tasks/include" -I"../../third-party/Processlib/core/include" -I"../../common/include" -I"../../hardware/include" -I"../../control/include" -I"../../control/software_operation/include" -pipe -fPIC -O2 -Wall -W -DNDEBUG -I. -I../core -I../../third-party/Processlib/sip -I/usr/local/lib/python2.7/site-packages/numpy/core/include -I/usr/local/include/python2.7 -I../../third-party/Processlib/tasks/include -I../../third-party/Processlib/core/include -I../../common/include -I../../hardware/include -I../../control/include -I../../control/software_operation/include -o siplimacoreDebObj.o siplimacoreDebObj.cpp
./siplimacoreDebObj.cpp: In constructor ‘sipDebObj::sipDebObj(lima::DebParams&, const std::string&, const std::string&, const std::string&, int)’:
./siplimacoreDebObj.cpp:98: error: no matching function for call to ‘lima::DebObj::DebObj(lima::DebParams&, const std::basic_string<char, std::char_traits<char>, std::allocator<char> >&, const std::basic_string<char, std::char_traits<char>, std::allocator<char> >&, const std::basic_string<char, std::char_traits<char>, std::allocator<char> >&, int&)’
../../common/include/lima/Debug.h:454: note: candidates are: lima::DebObj::DebObj(lima::DebParams&, bool, const char*, const char*, const char*, int)
../../common/include/lima/Debug.h:274: note:                 lima::DebObj::DebObj(const lima::DebObj&)
../../common/sip/Debug.sip: In function ‘void* init_type_DebObj(sipSimpleWrapper*, PyObject*, PyObject*, PyObject**, PyObject**, PyObject**)’:
../../common/sip/Debug.sip:275: error: invalid conversion from ‘lima::DebObj*’ to ‘sipDebObj*’
make[1]: *** [siplimacoreDebObj.o] Error 1
g++ -c -pthread -g -DWITH_SPS_IMAGE -I"." -I"../core" -I"../../third-party/Processlib/sip" -I"/usr/local/lib/python2.7/site-packages/numpy/core/include" -I"/usr/local/include/python2.7" -I"../../third-party/Processlib/tasks/include" -I"../../third-party/Processlib/core/include" -I"../../common/include" -I"../../hardware/include" -I"../../control/include" -I"../../control/software_operation/include" -pipe -fPIC -O2 -Wall -W -DNDEBUG -I. -I../core -I../../third-party/Processlib/sip -I/usr/local/lib/python2.7/site-packages/numpy/core/include -I/usr/local/include/python2.7 -I../../third-party/Processlib/tasks/include -I../../third-party/Processlib/core/include -I../../common/include -I../../hardware/include -I../../control/include -I../../control/software_operation/include -o siplimacoreDebParams.o siplimacoreDebParams.cpp
./siplimacoreDebParams.cpp: In constructor ‘sipDebParams::sipDebParams(lima::DebModule, const std::string&, const std::string&)’:
./siplimacoreDebParams.cpp:66: error: no matching function for call to ‘lima::DebParams::DebParams(lima::DebModule&, const std::basic_string<char, std::char_traits<char>, std::allocator<char> >&, const std::basic_string<char, std::char_traits<char>, std::allocator<char> >&)’
../../common/include/lima/Debug.h:352: note: candidates are: lima::DebParams::DebParams(lima::DebModule, const char*, const char*)
../../common/include/lima/Debug.h:139: note:                 lima::DebParams::DebParams(const lima::DebParams&)
../../common/sip/Debug.sip: In function ‘void* init_type_DebParams(sipSimpleWrapper*, PyObject*, PyObject*, PyObject**, PyObject**, PyObject**)’:
../../common/sip/Debug.sip:120: error: invalid conversion from ‘lima::DebParams*’ to ‘sipDebParams*’
make[1]: *** [siplimacoreDebParams.o] Error 1
```
And I don't know how to fix that up...

**Comment by sebastien-petitdemange** [comment]
Hi Georg,

Thanks you for your report, could create an issue on github.

We already seen this problem but unfortunately it'll take some time to
solve it. Could you downgrade sip in the meantime?

We'll let you know when we will resolved this issue.

Regards,

SEB

**Comment by birkenfeld** [comment]
Thanks for the reply! I'll then work with an older sip for now...
